### ISSUE TITLE
Python scripts fail, 'Out of gas'

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-visualization-tools#1]
Running:
```
python3 dex-visualization-tools/generate_plot_for_all_pairs.py DAI OWL
```
fails returning a traceback (see below). All token pairs are affected.

Traceback:
```
(venv) $ python3 plot_orderbook_tokenpair.py DAI OWL
Traceback (most recent call last):
  File "plot_orderbook_tokenpair.py", line 173, in <module>
    inst = util.read_instance_from_blockchain()
  File "/path/dex-visualization-tools/util.py", line 106, in read_instance_from_blockchain
    orders = contract_reader.get_orderbook()
  File "/path/dex-visualization-tools/contract_reader.py", line 82, in get_orderbook
    orders_encoded = contract.functions.getEncodedOrders().call()
  File "/path/dex-visualization-tools/venv/lib/python3.7/site-packages/web3/contract.py", line 904, in call
    **self.kwargs
  File "/path/dex-visualization-tools/venv/lib/python3.7/site-packages/web3/contract.py", line 1424, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/path/dex-visualization-tools/venv/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/path/dex-visualization-tools/venv/lib/python3.7/site-packages/web3/eth.py", line 426, in call
    [transaction, block_identifier],
  File "/path/dex-visualization-tools/venv/lib/python3.7/site-packages/web3/manager.py", line 152, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'Out of gas'}
```

**Comment by josojo** [comment]
The same issue also appeared in dex-contract. The orderbook got so big that even with the very high gas limits, we are getting this error.

The workaround is to implement the paginated page view,  as I have quickly done in JS

https://github.com/gnosis/dex-contracts/pull/563
 
Maybe someone fluent in python can do the same here.

**Comment by fleupold** [comment]
Alternatively, you could be using the BatchExchangeViewer wrapper contract which should be doing a lot of filtering right in the smart contract already. However, eventually it will require pagination as well.
